controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    cr5_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

cr5_group_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

gripper_controller:
  ros__parameters:
    joints:
      - robotiq_85_left_knuckle_joint
      - robotiq_85_right_knuckle_joint
      - robotiq_85_left_inner_knuckle_joint
      - robotiq_85_left_finger_tip_joint
      - robotiq_85_right_finger_tip_joint
      - robotiq_85_right_inner_knuckle_joint
    command_interfaces:
      - position 
    state_interfaces:
      - position
      - velocity
